import Layout from "../components/layout";
import Head from "next/head";
import {TOKEN, DATABASE_ID} from "../config";
import ProjectItem from "../components/projects/project-item";

export default function Project({projects}) {
    
    return(
        <>
            <Layout>
            <div className="flex flex-col items-center justify-center min-h-screnn px-5 mb-10 px-6">
                <Head>
                    <title>jeongho 포트폴리오</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <h1 className="text-4xl font-bold">총 프로젝트 : 
                <span className="pl-4 text-blue-300">{projects.results.length}</span>
                </h1>
                <div className="grid grid-cols-1 md:grid-cols-2 py-10 m-6 gap-8 w-full">
                {projects.results.map((aProject) =>  (
                    <ProjectItem key={aProject.id} data={aProject}/>
                ))}
                </div>
            </div>
            </Layout>
        </>
    )
}

//  getStaticProps은 빌드 타임에 호출이 된다.
// 데이터를 이미 가져온 다음에 화면에 렌더링이 된다.
export async function getStaticProps() {
    const options = {
        method: 'POST',
        headers: {
          accept: 'application/json',
          'Notion-Version': '2022-06-28',
          'content-type': 'application/json',
          Authorization: `Bearer ${TOKEN}`
        },
        body: JSON.stringify({
            sorts: [
                {
                    "property" : "project", 
                    "direction": "ascending" // 프로젝트 이름순으로 정렬하는 법
                }
            ],
            page_size: 100})
      };
      
      const res = await fetch(`https://api.notion.com/v1/databases/${DATABASE_ID}/query`, options)
    
      const projects = await res.json()

       //console.log(result)
    return{
        props: {projects},
        revalidate:1 // 데이터 변경이 있으면 갱신 1초마다 갱신
    }
}