import Layout from "../components/layout";
import Head from "next/head";

export default function Project() {
    return(
        <>
            <Layout>
                <Head>
                    <title>jeongho 포트폴리오</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
            </Layout>
        </>
    )
}